# Databricks Apps configuration
# See: https://docs.databricks.com/dev-tools/databricks-apps/
#
# This app uses user-based (OBO) authentication, meaning users can only
# access Genie Spaces they have permission to manage.
#
# The FastAPI server serves both:
# - Static React frontend files from /frontend/dist
# - REST API endpoints under /api

command:
  - "uvicorn"
  - "agent_server.start_server:app"
  - "--host"
  - "0.0.0.0"
  - "--port"
  - "8000"

env:
  - name: MLFLOW_TRACKING_URI
    value: "databricks"
  - name: MLFLOW_REGISTRY_URI
    value: "databricks-uc"
  - name: MLFLOW_EXPERIMENT_ID
    value: ""  # REQUIRED: Set to your MLflow experiment ID before deploying
  - name: LLM_MODEL
    value: "databricks-claude-sonnet-4"

# User authorization - enables OBO (On-behalf-of) authentication
# Users will be authenticated with their own credentials, ensuring they
# can only access Genie Spaces they have permission to access.
#
# NOTE: OBO requires workspace admin to enable the preview feature:
#   Settings > Previews > "On-behalf-of user authentication for Databricks Apps"
#
# Alternative: Add Genie Spaces as resources (see docs/deployment.md)
permissions:
  - permission: "user"
    scopes:
      - "dashboards.genie"
      - "serving-endpoints"
      - "sql"
