# Databricks Apps configuration
# See: https://docs.databricks.com/dev-tools/databricks-apps/
#
# This app uses user-based (OBO) authentication, meaning users can only
# access Genie Spaces they have permission to manage.
#
# The FastAPI server serves both:
# - Static React frontend files from /frontend/dist
# - REST API endpoints under /api

command:
  - "uvicorn"
  - "agent_server.start_server:app"
  - "--host"
  - "0.0.0.0"
  - "--port"
  - "8000"

env:
  - name: MLFLOW_TRACKING_URI
    value: "databricks"
  - name: MLFLOW_REGISTRY_URI
    value: "databricks-uc"
  - name: MLFLOW_EXPERIMENT_ID
    value: ""  # OPTIONAL: Set to your MLflow experiment ID to enable tracing
  - name: LLM_MODEL
    value: "databricks-claude-sonnet-4-5"
  - name: SQL_WAREHOUSE_ID
    value: ""  # Required for Optimize mode SQL execution
  - name: GENIE_TARGET_DIRECTORY
    value: ""  # Required for creating new Genie Spaces (e.g., /Workspace/Users/you@company.com/)
    
# Service Principal authorization
# The app uses its own service principal identity to access Databricks resources.
# You must grant the app's service principal access to:
#   1. Genie Spaces: Add SP with "Can Edit" permission
#   2. LLM Serving Endpoints: Add SP with "Can Query" permission
#   3. Target Directory (for creating new Genie Spaces): SP needs write permission
#
# Find the service principal in: Compute > Apps > [your app] > Authorization
# The SP name follows the pattern: app-XXXXX [app-name]
